Squashed commit of the following:
commit 3f765205800983c42402ea5cdb83c723d1ac9fa7
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Wed Jun 1 00:16:57 2022 -0700

    remove babel preset flow

commit 81a05e72157e5b009520b7eae8b74dfe147d8e0d
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 23:38:45 2022 -0700

    refactor, restore deleted code for simplification. test still passes

commit 96e87752b524e450ef722057d77d5b7353324722
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 23:28:39 2022 -0700

    remove extensionsToTreatAsEsm

commit 533619211e7f905789df7bb0d8b96529f965d034
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 23:16:46 2022 -0700

    removed createJestConfig from next/jest. different error

    error:
    ```
    TypeError: Cannot read property 'default' of undefined

           5 | import mockSafeAreaContext from 'react-native-safe-area-context/jest/mock';
           6 |
        >  7 | jest.mock('react-native-safe-area-context', () => mockSafeAreaContext);
             |                                                   ^
           8 |
           9 | describe('Index', () => {
          10 |   it('should render successfully', () => {
    ```

commit 03373cf65eff009c4dafc30f79829392ad1d2181
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 23:13:25 2022 -0700

    forced jest to read react-native-web as es module, by adding `type: module` to react-native-web package.json. got different error

    error:
    ```
     Validation Error:

      An unknown error occurred in react-native-web:

      module is not defined in ES module scope
    This file is being treated as an ES module because it has a '.js' file extension and '/home/user/MyProjects/nx-samples-rn/node_modules/react-native-web/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
      ReferenceError: module is not defined in ES module scope
    This file is being treated as an ES module because it has a '.js' file extension and '/home/user/MyProjects/nx-samples-rn/node_modules/react-native-web/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
        at file:///home/user/MyProjects/nx-samples-rn/node_modules/react-native-web/jest-preset.js:1:1
        at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
        at Loader.import (node:internal/modules/esm/loader:178:24)
        at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
        at requireOrImportModule (/home/user/MyProjects/nx-samples-rn/node_modules/jest-util/build/requireOrImportModule.js:65:32)
        at setupPreset (/home/user/MyProjects/nx-samples-rn/node_modules/jest-config/build/normalize.js:290:14)
        at normalize (/home/user/MyProjects/nx-samples-rn/node_modules/jest-config/build/normalize.js:709:15)
        at readConfig (/home/user/MyProjects/nx-samples-rn/node_modules/jest-config/build/index.js:236:45)

      Configuration Documentation:
      https://jestjs.io/docs/configuration
      ```

commit d9e10e5130d6d8490f29922327d23d2f5e530470
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 23:03:22 2022 -0700

    add rnw to transformIgnorePatterns. same err

    error:
    ```
    /home/user/MyProjects/nx-samples-rn/node_modules/react-native-web/dist/exports/StyleSheet/createCompileableStyle.js:11
        import normalizeValueWithProperty from './normalizeValueWithProperty';
        ^^^^^^

        SyntaxError: Cannot use import statement outside a module

          at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
          at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/utils/useResponsiveQuery/useResponsiveQuery.web.ts:2:1)
    ```

commit d76c71d7853b657fb2595332eba04552641bd9c5
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 22:58:53 2022 -0700

    simplify test.

    error:
    ```
    /home/user/MyProjects/nx-samples-rn/node_modules/react-native-web/dist/exports/StyleSheet/createCompileableStyle.js:11
        import normalizeValueWithProperty from './normalizeValueWithProperty';
        ^^^^^^

        SyntaxError: Cannot use import statement outside a module

          at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
          at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/utils/useResponsiveQuery/useResponsiveQuery.web.ts:2:1)
    ```

commit 8bfda9fb4f6a26ee252814e712cf55926e4df5c1
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 22:28:41 2022 -0700

    imported mock from test file instead of setup file.

    error:
    ```
    /home/user/MyProjects/nx-samples-rn/node_modules/react-native-web/dist/exports/StyleSheet/createCompileableStyle.js:11
        import normalizeValueWithProperty from './normalizeValueWithProperty';
        ^^^^^^

        SyntaxError: Cannot use import statement outside a module

          at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
          at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/utils/useResponsiveQuery/useResponsiveQuery.web.ts:2:1)
    ```

commit daeac9beb2db0d2e5fc383d5608eb692dba4b9af
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 22:14:51 2022 -0700

    added nx' "registerTsProject" to jest.setup.ts, as suggested in https://nx.dev/packages/jest#global-setupteardown-with-nx-libraries . Got same error.

    error:
    ```
    /home/user/MyProjects/nx-samples-rn/node_modules/react-native-safe-area-context/jest/mock.js:3
        import React from 'react';
        ^^^^^^

        SyntaxError: Cannot use import statement outside a module

          11 | import '@testing-library/jest-dom/extend-expect';
          12 |
        > 13 | import mockSafeAreaContext from 'react-native-safe-area-context/jest/mock';
             |                                                                           ^
          14 |
    ```

commit d8cf04ae8ca2330db852c47e32021bf8b3aa746d
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 22:11:45 2022 -0700

    renamed jest.setup to extension "ts". same error.

    error:
    ```
    /home/user/MyProjects/nx-samples-rn/node_modules/react-native-safe-area-context/jest/mock.js:3
        import React from 'react';
        ^^^^^^

        SyntaxError: Cannot use import statement outside a module

           6 | import '@testing-library/jest-dom/extend-expect';
           7 |
        >  8 | import mockSafeAreaContext from 'react-native-safe-area-context/jest/mock';
             |
    ```

commit 2fb5a6904fdfe8470eed078d2ed5d5ed9b945586
Author: Miguel Niblock <miguelniblock@posteo.net>
Date:   Tue May 31 22:09:07 2022 -0700

    add jest settings from working example. not working

    error:
    ```
    /home/user/MyProjects/nx-samples-rn/node_modules/react-native-safe-area-context/jest/mock.js:3
        import React from 'react';
        ^^^^^^

        SyntaxError: Cannot use import statement outside a module

           6 | import '@testing-library/jest-dom/extend-expect';
           7 |
        >  8 | import mockSafeAreaContext from 'react-native-safe-area-context/jest/mock';
             |
    ```